spring.application.name=customer-service
server.port=8056
spring.datasource.url=jdbc:h2:mem:customer-db
spring.cloud.discovery.enabled=true
eureka.instance.prefer-ip-address=true
spring.cloud.config.enabled=false
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp
