spring.application.name=ebank-bot
spring.ai.openai.api-key=${GROQ_API_KEY:}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=openai/gpt-oss-120b
spring.ai.openai.chat.options.reasoning-effort=low
server.port=8058
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
spring.ai.mcp.client.streamable-http.connections.customer.url=http://localhost:8056/mcp
spring.ai.mcp.client.streamable-http.connections.ebank.url=http://localhost:8057/mcp
discord.token=${DISCORD_TOKEN:}
telegram.token=${TELEGRAM_TOKEN:}
eureka.client.jersey.enabled=false
eureka.instance.prefer-ip-address=true
