spring.application.name=ebank-bot
spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.0-flash
server.port=8058
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
